virustotal_token = "77ac771d564647e8b2ca31621bf7b8afab67ddcb9cd03487ac54949799591f58"
fb_token = "477554842800359|KtwOJMaTR34AO7gq2Ly8jKgUkyk"
securitytrails_token = "w1huJXsjIXPvfBcBeuah8xS8L0DWaDkV"
spyse_token = ""
c99_api_key = "SG1ZE-8KAQC-TM7GX-7UCAR"
#slack_webhook = "https://hooks.slack.com/services/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"
discord_webhook = "https://discordapp.com/api/webhooks/624468835910680640/B3VthTjklLsgsCxwd44j0iOgW_v6ajQJOvnD_8dKsWOO2Uil1WhNftzsM1IxpcmVIZ1v"
postgres_connection = "postgresql://postgres:postgres@localhost:5432/"
telegrambot_token = ""
telegram_chat_id = ""
rate_limit = "5"
